require("global")
require("lazy-cfg")
require("lsp")
require("dap-cfg")
require("cmp-cfg")
require("nvtree")
require("spellcheck")
require("gitsign-cfg")

require("misc")
require("notebook")
require("colortheme")
vim.api.nvim_create_user_command("AddTags", function(opts)
  require("tags").add_tags(opts.args)
end, { nargs = 1 })
